### ISSUE TITLE
Redirection Segmental Fault

### ISSUE THREAD

**Issue by guoh27** [gmarcais/NoShell#2]
```c++
std::string text = "...";
noshell::Exit  command = "cat"_C() < text;
command.wait();
```
will throw segmental fault.

**Comment by guoh27** [comment]
Before line [noshell/noshell.hpp#L183](https://github.com/gmarcais/NoShell/blob/c63fe9d6b47346ecae392773cdabf11cccae2240/include/noshell/noshell.hpp#L183)
should insert `inline PipeLine& operator<(PipeLine& pl, const char* path) { return pl < from_to_path(0, path); }`, or it will loop unrolling template。

**Comment by gmarcais** [comment]
Thank you for the patch. This is now fixed in branch develop.

That said, `"cat"_C() << text;` works for `text` being a path to a file, not here-doc style input text.
